version: "3"
services:
  web:
    build:
      context: .
    ports:
      - "8080:8080"

  db:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=wi22254
      - MYSQL_USER=wi22254
      - MYSQL_PASSWORD=wi22254
    volumes:
      - wi22254-mysql-volume:/var/lib/mysql

volumes:
  wi22254-mysql-volume: