#Offizielle MySQL-Image als Basis verwenden

FROM  mysql:latest

# Umgebungsvariablen setzen
ENV MYSQL_ROOT_PASSWORD=admin
ENV MYSQL_DATABASE=meineDatenbank

#Port freigeben (Standard: 3306)
EXPOSE 3306

#Volumen für Datenbankdateien anlegen
VOLUME /var/lib/wi22254

#Startbefehl für MySQL-Server
CMD ["mysqld"]